package com.jack.dao;

import com.jack.model.Definition;
import com.jack.model.DefinitionExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DefinitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    long countByExample(DefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int deleteByExample(DefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int insert(Definition row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int insertSelective(Definition row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    List<Definition> selectByExample(DefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    Definition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int updateByExampleSelective(@Param("row") Definition row, @Param("example") DefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int updateByExample(@Param("row") Definition row, @Param("example") DefinitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int updateByPrimaryKeySelective(Definition row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_definition
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    int updateByPrimaryKey(Definition row);


    String getDefinitionByWord(String word);

    List<String> getThreeDefinitionsRandom();

    void setDefinition(@Param("word") String word, @Param("definition") String definition);

    void deleteByWord(@Param("word")String word);

}