package com.jack.model;

public class Definition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_definition.id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_definition.word_id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    private Integer wordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_definition.name
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_definition.id
     *
     * @return the value of tm_definition.id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_definition.id
     *
     * @param id the value for tm_definition.id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_definition.word_id
     *
     * @return the value of tm_definition.word_id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_definition.word_id
     *
     * @param wordId the value for tm_definition.word_id
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_definition.name
     *
     * @return the value of tm_definition.name
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_definition.name
     *
     * @param name the value for tm_definition.name
     *
     * @mbg.generated Mon Jun 05 21:58:01 EDT 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}